// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD8zFVO9agQcX9JQJuMftUInn70OCCTPQ',
    appId: '1:156183530541:web:ea20ffd9b1acb542607ca4',
    messagingSenderId: '156183530541',
    projectId: 'chattingapp-288b7',
    authDomain: 'chattingapp-288b7.firebaseapp.com',
    storageBucket: 'chattingapp-288b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAT4ek1aL14VC-kK-GUTHr70PIPJ19ap8',
    appId: '1:156183530541:android:789ba7c5fae0156f607ca4',
    messagingSenderId: '156183530541',
    projectId: 'chattingapp-288b7',
    storageBucket: 'chattingapp-288b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ1am-kL9tmVFNqqVXxZgYB-TNcfuN53k',
    appId: '1:156183530541:ios:45a83b26d4c282cd607ca4',
    messagingSenderId: '156183530541',
    projectId: 'chattingapp-288b7',
    storageBucket: 'chattingapp-288b7.appspot.com',
    iosBundleId: 'com.example.chattingAppV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ1am-kL9tmVFNqqVXxZgYB-TNcfuN53k',
    appId: '1:156183530541:ios:45a83b26d4c282cd607ca4',
    messagingSenderId: '156183530541',
    projectId: 'chattingapp-288b7',
    storageBucket: 'chattingapp-288b7.appspot.com',
    iosBundleId: 'com.example.chattingAppV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD8zFVO9agQcX9JQJuMftUInn70OCCTPQ',
    appId: '1:156183530541:web:2c3e0a4f00690189607ca4',
    messagingSenderId: '156183530541',
    projectId: 'chattingapp-288b7',
    authDomain: 'chattingapp-288b7.firebaseapp.com',
    storageBucket: 'chattingapp-288b7.appspot.com',
  );
}
